### ISSUE TITLE
Every single component suffers from the same warning

### ISSUE THREAD

**Issue by plusk** [dotkom/design-system#107]
>Missing return type on function.eslint(@typescript-eslint/explicit-function-return-type)

**Comment by FluidSense** [comment]
We _could_ change this rule, but it is nice to have a return type on most functions, although components are usually pretty straight forward.
Another solution is to set `JSX.Element` as return-type

**Comment by plusk** [comment]
Setting a return type is the correct answer, I just didn't have any luck with using `Element` earlier.
