### ISSUE TITLE
Change hosted URL

### ISSUE THREAD

**Issue by FluidSense** [dotkom/design-system#143]
Our current url `storybook.online.ntnu.no` is heavily locked to the framework we use.
In theory, we could create the design system without storybook, and who knows, someday we might change what we display our components with.
Thus, a more "neutral" url would make sense. 
Perhaps `design.online.ntnu.no` in the same style that NAV uses, `design.nav.no`.

**Comment by plusk** [comment]
I am also for this change, but for a simpler reason: people understand design, but random students have no idea what storybook means.

**Comment by FluidSense** [comment]
Fixed as of 30.9.2020!
