### ISSUE TITLE
Indent issue on story source codes

### ISSUE THREAD

**Issue by niklasmh** [dotkom/design-system#99]
## Describe the bug
The source code in the storybook examples is misformatted.

This is probably a core storybook problem as someone else has already filed an issue on the topic: https://github.com/storybookjs/storybook/issues/8078

## To Reproduce
1. Go to http://storybook.online.ntnu.no
2. Navigate to `Feedback` -> `Spinner` -> `Show code`

## Expected behavior
We want a pretty output:
![image](https://user-images.githubusercontent.com/8504538/66514109-ccbaa700-eadc-11e9-9e66-a7963c4880bd.png)

## Screenshots
Thus we are getting this instead:
![image](https://user-images.githubusercontent.com/8504538/66514072-bc0a3100-eadc-11e9-91ce-53225bff926a.png)

**Comment by kharann** [comment]
Doesnt storybook have a linter?

**Comment by niklasmh** [comment]
It is a `@storybook/addon-docs` problem, meaning it should probably be fixed by them. But if anyone here wants to debug and track down the core issue, you are more than welcome😄 It is still [hacktober](https://hacktoberfest.digitalocean.com/), so if you are up for a challenge, go for it!

They have it on their TODO, so they will hopefully fix it in the future:
![image](https://user-images.githubusercontent.com/8504538/67947734-97d5d780-fbe4-11e9-896c-f3d963be0207.png)
